### ISSUE TITLE
[feat] Enable compression middleware for Traefik

### ISSUE THREAD

**Issue by pascaliske** [pascaliske/infrastructure#460]
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: compress
  namespace: traefik
spec:
  compress: {}
```
